# Default values for kubernetes-replicator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: quay.io/mittwald/kubernetes-replicator
  tag: stable
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

resources:
  requests:
    memory: 32Mi
    cpu: 50m
  limits:
    memory: 128Mi
    cpu: 100m

nodeSelector: {}

tolerations: []

affinity: {}
